version: '3'
services:
  majale:
    build: .
    ports:
      - "8552:7856"
  #MySQL Service
  db:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3206:3306"
    environment:
      MYSQL_DATABASE: majale
      MYSQL_USER: geeksesi
      MYSQL_PASSWORD: fjbcsDX9
      MYSQL_ROOT_PASSWORD: x7rYYtXq
    volumes:
      - mysqldata:/var/lib/mysql/
    networks:
      - mynet

#Docker Networks
networks:
  mynet:
    driver: bridge
#Volumes
volumes:
  mysqldata:
    driver: local